### ISSUE TITLE
Adjust clickable area for Abuse type labels on requesters/new

### ISSUE THREAD

**Issue by abachman** [rubyforgood/voices-of-consent#144]
looks like the toggle behavior for the abuse type labels only toggle the first checkbox

**Comment by MxOliver** [comment]
Hey, I'd love to work on this if it's still open

**Comment by MxOliver** [comment]
@abachman Can you post the route for the page with these checkboxes? I tried /box_request_abuse_types and /box_request_abuse_types/new and /box_request and /box_request/new but all I see are text fields

**Comment by abachman** [comment]
hey @MxOliver, welcome!

yeah, the routing in the app right now is kind of chaotic, we did a **big** one weekend push to stub out a bunch of stuff, and will be refining as we go. 

At the moment, the form you're looking for is at `/requesters/new`.

**Comment by MxOliver** [comment]
I think this issue might have resolved itself? I am having trouble replicating it. All the checkboxes are toggling

**Comment by maebeale** [comment]
@MxOliver so, the checkboxes themselves seem to work fine, but clicking the text to the right only works for the first item, so that's why it was originally reported. So, maybe the update on this is that all the words should be included in the clickable area of the checkboxes? 

Also, I noticed a separate issue w the All of the Above: When checked it should check-all and remove-all the other checkmarks when unchecked. Will add that as a new issue.

**Comment by MxOliver** [comment]
Ohh I see, okay I'm on it
