### ISSUE TITLE
Add college student section to Volunteer form

### ISSUE THREAD

**Issue by maebeale** [rubyforgood/voices-of-consent#285]
- Add :university_location and :graduation_year to Volunteer form
- UniversityLocation assn needs to be added to the model
- Ideally the form would have a select2 dropdown of existing university Locations in the db, but allows the user to add a new one
- Graduation year dropdown should include 1950-2035. (Ideally it's a type-ahead feature as well)

**Comment by maebeale** [comment]
@nathandonato

**Comment by nathandonato** [comment]
@maebeale I can't find a `UniversityLocation` model. Looking at `schema.rb`, it looks like `volunteers.university_location_id` is a foreign key referencing the `locations` table. But the `Location` model's `location_type` enum doesn't support anything like "university." Should I add this enum type?

**Comment by maebeale** [comment]
Yes, please on the enum type! Thank you!

**Comment by nathandonato** [comment]
Thanks, @maebeale. I have started work on this, so feel free to assign me.

**Comment by nathandonato** [comment]
Hi @maebeale I opened up a PR. Please note it adds most but not all of the things requested in this issue. I decided to open up the PR anyway because I won't have much time to work on this in the coming days. 

New issues will be needed for: 1) creating a new Location from within the form and 2) adding a graduation year dropdown.

**Comment by maebeale** [comment]
just completed creating those as new issues, @nathandonato. thank you!
