### ISSUE TITLE
Make sure "invited and accepted" header is populating on Users index

### ISSUE THREAD

**Issue by maebeale** [rubyforgood/voices-of-consent#426]
In prod this column is completely empty. Please check that invited && accepted is displaying correctly and fix if necessary.

**Comment by mikeg1440** [comment]
Hi I'm taking a look at this bug and just had a couple questions.  I see the current code looks like this 
```
<table class="table">
  <tr>
    <th>Email</th>
    <th>Invited and accepted?</th>
  </tr>
  <% User.all.each do |user| %>
    <tr>
      <td> <%= user.email %> </td>
      <td>
        <% if user.invitation_sent_at? %>
          <%= user.invitation_accepted? %>
        <% end %>
      </td>
   </tr>
  <% end %>
</table>
```
I was just wondering what the desired result would be if the invitation has not been sent yet, because right now it will just be blank.  Removing the if statement allows this to display false if invitation has not been sent but I just want to make sure that is the desired result before submitting a PR.

**Comment by maebeale** [comment]
Thank you! I think rather than removing the `if`, my vote would be to add an `else` that says "not invited" or something. What would you expect to see here?
